
# Loop constraints
directive set /gauss_blur/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /gauss_blur/core/core:rlp/main CSTEPS_FROM {{. == 3} {.. == 0}}

# IO operation constraints
directive set /gauss_blur/core/core:rlp/main/MAC1:asn#17 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:asn#18 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:asn#22 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:asn#26 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:asn#27 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:asn#31 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:asn#35 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:asn#36 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:asn#40 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#271 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#272 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#273 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#274 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#275 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#276 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#277 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#1 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#2 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#3 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#4 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#5 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#6 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#7 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#8 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#9 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#10 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#11 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#12 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#13 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#14 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#15 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#16 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#17 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#18 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#19 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#4:asn#20 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#284 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#285 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#286 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#287 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#288 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#289 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#290 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/asn#291 CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/io_write(volume:rsc.d) CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/io_write(vout:rsc.d) CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/vin:asn(regs.regs(0).sva) CSTEPS_FROM {{.. == 2}}

# Real operation constraints
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#42 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#41 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#45 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#44 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#47 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#43 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#46 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#49 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#48 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#52 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#51 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#54 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#50 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#53 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#39 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#56 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#55 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#59 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#58 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#61 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#57 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#60 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/MAC1:acc#40 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#3:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#3:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#3:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/acc#16 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#3:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#3:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#3:acc CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/and CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/and#2 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/and#3 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/and#4 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/and#5 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/and#6 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#5:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/aif#1:acc CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/aif#3:aif:acc CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#5:acc CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#5:mux#2 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/aif#11:acc CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/aif#13:aif:acc CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#6:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/aif#17:aif:acc CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/if#6:acc CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/mux#6 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/acc#2 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/mux#7 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/mux#8 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/acc#3 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/mux#10 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/mux#11 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/deltax_square_red:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/deltax_square_blue:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/aif#39:acc CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/deltay_square_red:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/aif#41:aif:acc CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/aif#45:acc CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/deltay_square_blue:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/aif#47:aif:acc CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/volume_current:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/acc#9 CSTEPS_FROM {{.. == 1}}
directive set /gauss_blur/core/core:rlp/main/volume_current:acc#4 CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/volume_current:acc CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/volume_current:acc#5 CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/volume_current:acc#2 CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/volume_current:acc#6 CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/volume_current:acc#7 CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/volume_current:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/if#17:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/acc#12 CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/if#17:acc CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/and#15 CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/nor#1 CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/nor CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/and#14 CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/and#12 CSTEPS_FROM {{.. == 2}}
directive set /gauss_blur/core/core:rlp/main/or#4 CSTEPS_FROM {{.. == 2}}
