
# Loop constraints
directive set /sobel_filter_bw/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /sobel_filter_bw/core/core:rlp/main CSTEPS_FROM {{. == 3} {.. == 0}}

# IO operation constraints
directive set /sobel_filter_bw/core/core:rlp/main/regs.regs:asn CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/regs.regs:asn#1 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/regs.regs:asn#2 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/regs.regs:asn#3 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/regs.regs:asn#4 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/regs.regs:asn#5 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/regs.regs:asn#6 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/regs.regs:asn#7 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/regs.regs:asn#8 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/io_write(vout:rsc.d) CSTEPS_FROM {{.. == 2}}
directive set /sobel_filter_bw/core/core:rlp/main/vin:asn(regs.regs(0).sva) CSTEPS_FROM {{.. == 2}}

# Real operation constraints
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#18 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-1:acc CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#20 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#19 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#22 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#21 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#23 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#24 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-1:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#28 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#33 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#30 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#32 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#25 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#26 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#27 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#29 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#31 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-1:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#34 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-1:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#36 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#35 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#38 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#37 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#39 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-1:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#40 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-1:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#41 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-1:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#43 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#42 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#45 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#44 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#46 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-1:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#47 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-1:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#51 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#56 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#53 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#55 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#48 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#49 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#50 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#52 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#54 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-1:acc#18 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#57 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-2:acc CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#59 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#58 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#61 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#60 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#62 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#63 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-2:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#64 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-2:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#66 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#65 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#68 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#67 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#69 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-2:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#70 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-2:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#71 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-3:acc CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#73 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#72 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#75 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#74 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#76 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-3:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#77 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-3:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#81 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#86 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#83 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#85 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#78 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#79 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#80 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#82 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#84 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-3:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#87 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-3:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#89 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#88 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#91 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#90 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#92 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-3:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#93 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-3:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#94 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-3:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#96 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#95 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#98 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#97 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#99 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-3:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#100 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-3:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#104 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#109 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#106 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#108 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#101 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#102 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#103 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#105 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#107 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1-3:acc#18 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:mul#4 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#139 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#138 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#141 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:mul#1 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#133 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:mul#3 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#135 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#137 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:mul#2 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#119 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#118 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#127 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#126 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#129 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#117 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#116 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#123 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#115 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#142 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#114 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#122 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#125 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#113 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#112 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#121 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#111 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#143 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#110 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#120 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#124 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#128 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#130 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#132 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:mul CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#131 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#134 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#136 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#140 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc CSTEPS_FROM {{.. == 2}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#48 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#47 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#50 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#17 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:mul#6 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#26 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#25 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#32 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#24 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#144 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#23 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#31 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#35 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#22 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#21 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#30 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#20 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/ACC1:acc#145 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#19 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#29 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#34 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#37 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#39 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#36 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#28 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#27 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#33 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#38 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#41 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#42 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#44 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#14 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:mul CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#40 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:mul#4 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#43 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#45 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#16 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:mul#5 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#46 CSTEPS_FROM {{.. == 2}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#18 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:mul#7 CSTEPS_FROM {{.. == 1}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#49 CSTEPS_FROM {{.. == 2}}
directive set /sobel_filter_bw/core/core:rlp/main/MAC2:acc#13 CSTEPS_FROM {{.. == 2}}
directive set /sobel_filter_bw/core/core:rlp/main/abs:if:acc CSTEPS_FROM {{.. == 2}}
directive set /sobel_filter_bw/core/core:rlp/main/abs#1:if:acc CSTEPS_FROM {{.. == 2}}
directive set /sobel_filter_bw/core/core:rlp/main/abs:mux#1 CSTEPS_FROM {{.. == 2}}
directive set /sobel_filter_bw/core/core:rlp/main/abs#1:mux#1 CSTEPS_FROM {{.. == 2}}
directive set /sobel_filter_bw/core/core:rlp/main/acc#12 CSTEPS_FROM {{.. == 2}}
directive set /sobel_filter_bw/core/core:rlp/main/if#5:acc CSTEPS_FROM {{.. == 2}}
