
# Loop constraints
directive set /markers/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /markers/core/core:rlp/main CSTEPS_FROM {{. == 7} {.. == 0}}

# IO operation constraints
directive set /markers/core/core:rlp/main/asn#170 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#171 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#172 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#173 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#174 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#175 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#176 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#1 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#2 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#3 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#4 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#5 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#6 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#7 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#8 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#9 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#10 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#11 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#12 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#13 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#14 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#15 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#16 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#17 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#18 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#19 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#20 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#181 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#182 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#183 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#184 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#185 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#186 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/asn#187 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/asn#188 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/asn#189 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/asn#190 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/asn#191 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/asn#192 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/asn#193 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/asn#194 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/asn#195 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/asn#196 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/asn#202 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/asn#203 CSTEPS_FROM {{.. == 4}}
directive set /markers/core/core:rlp/main/asn#204 CSTEPS_FROM {{.. == 5}}
directive set /markers/core/core:rlp/main/asn#205 CSTEPS_FROM {{.. == 5}}
directive set /markers/core/core:rlp/main/io_write(volume:rsc.d) CSTEPS_FROM {{.. == 6}}
directive set /markers/core/core:rlp/main/io_write(vout:rsc.d) CSTEPS_FROM {{.. == 6}}

# Real operation constraints
directive set /markers/core/core:rlp/main/if:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/acc#6 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if:acc CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/and CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/and#1 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/and#2 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/and#3 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#2:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#2:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#2:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/aif#3:aif:acc CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#2:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/aif#7:aif:acc CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/if#2:acc CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/else#2:acc CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/else#2:aif:acc CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/else#2:aif#1:acc CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/else#2:aif#1:aif:acc CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/else#2:aif#2:acc CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/else#2:if:acc#2 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/else#2:if:acc CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/mux#4 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/mux#5 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/mux#11 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/mux#12 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/mux#15 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/mux#16 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/mux#17 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/deltax_red:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/if#9:acc CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/aif#27:acc CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/mux#19 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/mux#20 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/deltax_square_red:acc#1 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/acc#4 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/if#10:acc CSTEPS_FROM {{.. == 4}}
directive set /markers/core/core:rlp/main/deltay_square_red:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /markers/core/core:rlp/main/aif#31:acc CSTEPS_FROM {{.. == 4}}
directive set /markers/core/core:rlp/main/if#10:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /markers/core/core:rlp/main/deltax_blue:acc#1 CSTEPS_FROM {{.. == 5}}
directive set /markers/core/core:rlp/main/else#10:acc CSTEPS_FROM {{.. == 5}}
directive set /markers/core/core:rlp/main/else#10:if:acc CSTEPS_FROM {{.. == 5}}
directive set /markers/core/core:rlp/main/deltay_blue:acc#1 CSTEPS_FROM {{.. == 5}}
directive set /markers/core/core:rlp/main/else#10:aif#1:acc CSTEPS_FROM {{.. == 6}}
directive set /markers/core/core:rlp/main/else#10:if:acc#1 CSTEPS_FROM {{.. == 6}}
