// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   mf2915@EEWS104A-015
//  Generated date: Wed May 04 15:44:28 2016
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    markers_core
// ------------------------------------------------------------------


module markers_core (
  vin, vga_xy, clk, en, arst_n, vout_rsc_mgc_out_stdreg_d
);
  input [89:0] vin;
  input [19:0] vga_xy;
  input clk;
  input en;
  input arst_n;
  output [29:0] vout_rsc_mgc_out_stdreg_d;
  reg [29:0] vout_rsc_mgc_out_stdreg_d;



  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : core
    // Interconnect Declarations
    reg [3:0] acc_4_0_sva;
    reg [9:0] green_xy_0_sva;
    reg [9:0] green_xy_1_sva;
    reg [5:0] acc_imod_sva;
    reg [3:0] if_acc_1_psp_sva;
    reg [3:0] if_acc_svs;
    reg land_sva_1;
    reg land_lpi_1_dfm;
    reg slc_svs;
    reg land_3_sva_1;
    reg land_3_lpi_1_dfm;
    reg aif_3_slc_svs;
    reg aif_3_land_sva_1;
    reg land_2_lpi_1_dfm;
    reg aif_7_slc_svs;
    reg aif_7_land_sva_1;
    reg [3:0] acc_4_0_sva_dfm_1;
    reg if_4_land_lpi_1_dfm;
    reg [9:0] green_xy_0_sva_2;
    reg [9:0] green_xy_1_sva_2;
    reg [9:0] green_xy_0_sva_dfm_2;
    reg [9:0] green_xy_1_sva_dfm_2;
    reg [10:0] deltax_acc_psp_sva;
    reg slc_3_svs;
    reg land_5_sva_1;
    reg land_5_lpi_1_dfm;
    reg [10:0] deltay_acc_psp_sva;
    reg aif_25_slc_svs;
    reg aif_25_land_sva_1;
    reg [3:0] acc_4_0_sva_dfm_2;
    reg [9:0] green_xy_0_sva_dfm_3;
    reg [9:0] green_xy_1_sva_dfm_3;
    reg land_2_lpi_1_dfm_1;
    reg aif_7_slc_svs_1;
    reg [9:0] green_xy_1_sva_dfm_4;
    reg [10:0] deltax_acc_psp_sva_1;
    reg land_5_lpi_1_dfm_1;
    reg aif_25_slc_svs_1;
    reg aif_7_slc_svs_st;
    reg land_5_lpi_1_dfm_st;
    reg aif_25_slc_svs_st;
    reg [8:0] if_7_slc_deltay_itm;
    reg [8:0] if_7_slc_deltay_itm_1;
    reg land_2_lpi_1_dfm_st_1;
    reg aif_7_slc_svs_st_1;
    reg land_5_lpi_1_dfm_st_1;
    reg aif_25_slc_svs_st_1;
    reg main_stage_0_2;
    reg main_stage_0_3;
    reg main_stage_0_4;
    reg nand_cse;

    reg[9:0] select_0;
    begin : core_rlpExit
      forever begin : core_rlp
        // C-Step 0 of Loop 'core_rlp'
        acc_4_0_sva = 4'b0;
        green_xy_0_sva = 10'b0;
        green_xy_1_sva = 10'b0;
        main_stage_0_2 = 1'b0;
        main_stage_0_3 = 1'b0;
        main_stage_0_4 = 1'b0;
        begin : mainExit
          forever begin : main
            // C-Step 0 of Loop 'main'
            begin : waitLoop0Exit
              forever begin : waitLoop0
                @(posedge clk or negedge ( arst_n ));
                if ( ~ arst_n )
                  disable core_rlpExit;
                if ( en )
                  disable waitLoop0Exit;
              end
            end
            // C-Step 1 of Loop 'main'
            if ( main_stage_0_4 ) begin
              aif_25_land_sva_1 = 1'b0;
              if ( land_5_lpi_1_dfm_st_1 ) begin
                if ( aif_25_slc_svs_st_1 ) begin
                  aif_25_land_sva_1 = readslicef_10_1_9((conv_u2s_9_10(if_7_slc_deltay_itm_1)
                      + 10'b1111110001));
                end
              end
              vout_rsc_mgc_out_stdreg_d <= {(signext_10_1(aif_25_land_sva_1 & aif_25_slc_svs_1
                  & land_5_lpi_1_dfm_1)) , 20'b0};
            end
            if ( main_stage_0_3 ) begin
              land_5_sva_1 = 1'b0;
              slc_3_svs = readslicef_11_1_10(((~ deltax_acc_psp_sva_1) + 11'b1));
              if ( slc_3_svs ) begin
                land_5_sva_1 = readslicef_10_1_9((conv_u2s_9_10(deltax_acc_psp_sva_1[9:1])
                    + 10'b1111110001));
              end
              land_5_lpi_1_dfm = land_5_sva_1 & slc_3_svs;
              land_5_lpi_1_dfm_st = land_5_lpi_1_dfm;
              if ( land_5_lpi_1_dfm ) begin
                deltay_acc_psp_sva = readslicef_12_11_1((({1'b1 , (vga_xy[19:10])
                    , 1'b1}) + conv_u2s_11_12({(~ green_xy_1_sva_dfm_4) , 1'b1})));
                aif_25_slc_svs = readslicef_11_1_10(((~ deltay_acc_psp_sva) + 11'b1));
                aif_25_slc_svs_st = aif_25_slc_svs;
                if ( aif_25_slc_svs ) begin
                  if_7_slc_deltay_itm = deltay_acc_psp_sva[9:1];
                end
              end
            end
            if ( main_stage_0_2 ) begin
              green_xy_1_sva_2 = 10'b0;
              green_xy_0_sva_2 = 10'b0;
              aif_7_land_sva_1 = 1'b0;
              if ( land_2_lpi_1_dfm_st_1 ) begin
                if ( aif_7_slc_svs_st_1 ) begin
                end
                else begin
                  aif_7_land_sva_1 = ~ (readslicef_9_1_8((({1'b1 , (~ (vin[9:2]))})
                      + 9'b1101101)));
                end
              end
              if ( aif_7_land_sva_1 & (~ aif_7_slc_svs_1) & land_2_lpi_1_dfm_1 )
                  begin
                acc_4_0_sva_dfm_1 = acc_4_0_sva_dfm_2 + 4'b1;
              end
              else begin
                acc_4_0_sva_dfm_1 = acc_4_0_sva_dfm_2;
              end
              if ( acc_4_0_sva_dfm_1[3] ) begin
                if_4_land_lpi_1_dfm = ~((green_xy_1_sva_dfm_3[9]) | (green_xy_1_sva_dfm_3[8])
                    | (green_xy_1_sva_dfm_3[7]) | (green_xy_1_sva_dfm_3[6]) | (green_xy_1_sva_dfm_3[5])
                    | (green_xy_1_sva_dfm_3[4]) | (green_xy_1_sva_dfm_3[3]) | (green_xy_1_sva_dfm_3[2])
                    | (green_xy_1_sva_dfm_3[1]) | (green_xy_1_sva_dfm_3[0]) | (green_xy_0_sva_dfm_3[9])
                    | (green_xy_0_sva_dfm_3[8]) | (green_xy_0_sva_dfm_3[7]) | (green_xy_0_sva_dfm_3[6])
                    | (green_xy_0_sva_dfm_3[5]) | (green_xy_0_sva_dfm_3[4]) | (green_xy_0_sva_dfm_3[3])
                    | (green_xy_0_sva_dfm_3[2]) | (green_xy_0_sva_dfm_3[1]) | (green_xy_0_sva_dfm_3[0]));
                if ( if_4_land_lpi_1_dfm ) begin
                  green_xy_0_sva_2 = vga_xy[9:0];
                  green_xy_1_sva_2 = vga_xy[19:10];
                end
              end
              nand_cse = ~((~((~ if_4_land_lpi_1_dfm) & (acc_4_0_sva_dfm_1[3])))
                  & (acc_4_0_sva_dfm_1[3]));
              green_xy_0_sva_dfm_2 = MUX_v_10_2_2({green_xy_0_sva_2 , green_xy_0_sva_dfm_3},
                  nand_cse);
              green_xy_1_sva_dfm_2 = MUX_v_10_2_2({green_xy_1_sva_2 , green_xy_1_sva_dfm_3},
                  nand_cse);
              deltax_acc_psp_sva = readslicef_12_11_1((({1'b1 , (vga_xy[9:0]) , 1'b1})
                  + conv_u2s_11_12({(~ green_xy_0_sva_dfm_2) , 1'b1})));
              acc_4_0_sva = acc_4_0_sva_dfm_1;
              green_xy_0_sva = green_xy_0_sva_dfm_2;
              green_xy_1_sva = green_xy_1_sva_dfm_2;
            end
            aif_3_land_sva_1 = 1'b0;
            land_3_sva_1 = 1'b0;
            land_sva_1 = 1'b0;
            acc_imod_sva = conv_s2s_5_6(({3'b100 , (vga_xy[9:8])}) + conv_u2s_4_5(readslicef_5_4_1((conv_u2u_4_5({(vga_xy[2:0])
                , 1'b1}) + conv_u2u_4_5(vga_xy[6:3]))))) + conv_u2s_5_6({(conv_u2u_1_2(~
                (vga_xy[3])) + conv_u2u_1_2(~ (vga_xy[7]))) , 2'b0 , (readslicef_2_1_1((conv_u2u_1_2(vga_xy[7])
                + 2'b1)))});
            if_acc_1_psp_sva = (readslicef_5_4_1((({(~ (acc_imod_sva[3])) , 4'b1})
                + conv_s2u_3_5(acc_imod_sva[5:3])))) + ({1'b1 , (acc_imod_sva[2:0])});
            if_acc_svs = conv_s2u_1_4(if_acc_1_psp_sva[3]) + if_acc_1_psp_sva;
            select_0 = vga_xy[19:10];
            case (select_0)
              10'b0 : begin
                land_sva_1 = ~((vga_xy[9]) | (vga_xy[8]) | (vga_xy[7]) | (vga_xy[6])
                    | (vga_xy[5]) | (vga_xy[4]) | (vga_xy[3]) | (vga_xy[2]) | (vga_xy[1])
                    | (vga_xy[0]));
              end
              default : begin
                // NOP
              end
            endcase
            land_lpi_1_dfm = land_sva_1 & (~((vga_xy[19]) | (vga_xy[18]) | (vga_xy[17])
                | (vga_xy[16]) | (vga_xy[15]) | (vga_xy[14]) | (vga_xy[13]) | (vga_xy[12])
                | (vga_xy[11]) | (vga_xy[10])));
            slc_svs = readslicef_5_1_4((conv_u2u_4_5(vin[29:26]) + 5'b11011));
            if ( slc_svs ) begin
            end
            else begin
              land_3_sva_1 = ~ (readslicef_8_1_7((({1'b1 , (~ (vin[29:23]))}) + 8'b1001001)));
            end
            land_3_lpi_1_dfm = land_3_sva_1 & (~ slc_svs);
            if ( land_3_lpi_1_dfm ) begin
              aif_3_slc_svs = readslicef_8_1_7((conv_u2u_7_8(vin[19:13]) + 8'b10110101));
              if ( aif_3_slc_svs ) begin
              end
              else begin
                aif_3_land_sva_1 = ~ (readslicef_8_1_7((conv_u2s_7_8(~ (vin[18:12]))
                    + 8'b11100111)));
              end
            end
            land_2_lpi_1_dfm = aif_3_land_sva_1 & (~ aif_3_slc_svs) & land_3_lpi_1_dfm;
            if ( land_2_lpi_1_dfm ) begin
              aif_7_slc_svs = readslicef_8_1_7((conv_u2u_7_8(vin[9:3]) + 8'b11110001));
              aif_7_slc_svs_st = aif_7_slc_svs;
            end
            acc_4_0_sva_dfm_2 = acc_4_0_sva & (signext_4_1((if_acc_svs[3]) | (if_acc_svs[2])
                | (if_acc_svs[1]) | (if_acc_svs[0])));
            green_xy_0_sva_dfm_3 = green_xy_0_sva & (signext_10_1(~ land_lpi_1_dfm));
            green_xy_1_sva_dfm_3 = green_xy_1_sva & (signext_10_1(~ land_lpi_1_dfm));
            land_2_lpi_1_dfm_1 = land_2_lpi_1_dfm;
            aif_7_slc_svs_1 = aif_7_slc_svs;
            green_xy_1_sva_dfm_4 = green_xy_1_sva_dfm_2;
            deltax_acc_psp_sva_1 = deltax_acc_psp_sva;
            land_5_lpi_1_dfm_1 = land_5_lpi_1_dfm;
            aif_25_slc_svs_1 = aif_25_slc_svs;
            if_7_slc_deltay_itm_1 = if_7_slc_deltay_itm;
            land_2_lpi_1_dfm_st_1 = land_2_lpi_1_dfm;
            aif_7_slc_svs_st_1 = aif_7_slc_svs_st;
            land_5_lpi_1_dfm_st_1 = land_5_lpi_1_dfm_st;
            aif_25_slc_svs_st_1 = aif_25_slc_svs_st;
            main_stage_0_4 = main_stage_0_3;
            main_stage_0_3 = main_stage_0_2;
            main_stage_0_2 = 1'b1;
          end
        end
      end
    end
    nand_cse = 1'b0;
    main_stage_0_4 = 1'b0;
    main_stage_0_3 = 1'b0;
    main_stage_0_2 = 1'b0;
    aif_25_slc_svs_st_1 = 1'b0;
    land_5_lpi_1_dfm_st_1 = 1'b0;
    aif_7_slc_svs_st_1 = 1'b0;
    land_2_lpi_1_dfm_st_1 = 1'b0;
    if_7_slc_deltay_itm_1 = 9'b0;
    if_7_slc_deltay_itm = 9'b0;
    aif_25_slc_svs_st = 1'b0;
    land_5_lpi_1_dfm_st = 1'b0;
    aif_7_slc_svs_st = 1'b0;
    aif_25_slc_svs_1 = 1'b0;
    land_5_lpi_1_dfm_1 = 1'b0;
    deltax_acc_psp_sva_1 = 11'b0;
    green_xy_1_sva_dfm_4 = 10'b0;
    aif_7_slc_svs_1 = 1'b0;
    land_2_lpi_1_dfm_1 = 1'b0;
    green_xy_1_sva_dfm_3 = 10'b0;
    green_xy_0_sva_dfm_3 = 10'b0;
    acc_4_0_sva_dfm_2 = 4'b0;
    aif_25_land_sva_1 = 1'b0;
    aif_25_slc_svs = 1'b0;
    deltay_acc_psp_sva = 11'b0;
    land_5_lpi_1_dfm = 1'b0;
    land_5_sva_1 = 1'b0;
    slc_3_svs = 1'b0;
    deltax_acc_psp_sva = 11'b0;
    green_xy_1_sva_dfm_2 = 10'b0;
    green_xy_0_sva_dfm_2 = 10'b0;
    green_xy_1_sva_2 = 10'b0;
    green_xy_0_sva_2 = 10'b0;
    if_4_land_lpi_1_dfm = 1'b0;
    acc_4_0_sva_dfm_1 = 4'b0;
    aif_7_land_sva_1 = 1'b0;
    aif_7_slc_svs = 1'b0;
    land_2_lpi_1_dfm = 1'b0;
    aif_3_land_sva_1 = 1'b0;
    aif_3_slc_svs = 1'b0;
    land_3_lpi_1_dfm = 1'b0;
    land_3_sva_1 = 1'b0;
    slc_svs = 1'b0;
    land_lpi_1_dfm = 1'b0;
    land_sva_1 = 1'b0;
    if_acc_svs = 4'b0;
    if_acc_1_psp_sva = 4'b0;
    acc_imod_sva = 6'b0;
    green_xy_1_sva = 10'b0;
    green_xy_0_sva = 10'b0;
    acc_4_0_sva = 4'b0;
    vout_rsc_mgc_out_stdreg_d <= 30'b0;
  end


  function [0:0] readslicef_10_1_9;
    input [9:0] vector;
    reg [9:0] tmp;
  begin
    tmp = vector >> 9;
    readslicef_10_1_9 = tmp[0:0];
  end
  endfunction


  function [9:0] signext_10_1;
    input [0:0] vector;
  begin
    signext_10_1= {{9{vector[0]}}, vector};
  end
  endfunction


  function [0:0] readslicef_11_1_10;
    input [10:0] vector;
    reg [10:0] tmp;
  begin
    tmp = vector >> 10;
    readslicef_11_1_10 = tmp[0:0];
  end
  endfunction


  function [10:0] readslicef_12_11_1;
    input [11:0] vector;
    reg [11:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_12_11_1 = tmp[10:0];
  end
  endfunction


  function [0:0] readslicef_9_1_8;
    input [8:0] vector;
    reg [8:0] tmp;
  begin
    tmp = vector >> 8;
    readslicef_9_1_8 = tmp[0:0];
  end
  endfunction


  function [9:0] MUX_v_10_2_2;
    input [19:0] inputs;
    input [0:0] sel;
    reg [9:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[19:10];
      end
      1'b1 : begin
        result = inputs[9:0];
      end
      default : begin
        result = inputs[19:10];
      end
    endcase
    MUX_v_10_2_2 = result;
  end
  endfunction


  function [3:0] readslicef_5_4_1;
    input [4:0] vector;
    reg [4:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_5_4_1 = tmp[3:0];
  end
  endfunction


  function [0:0] readslicef_2_1_1;
    input [1:0] vector;
    reg [1:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_2_1_1 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_5_1_4;
    input [4:0] vector;
    reg [4:0] tmp;
  begin
    tmp = vector >> 4;
    readslicef_5_1_4 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_8_1_7;
    input [7:0] vector;
    reg [7:0] tmp;
  begin
    tmp = vector >> 7;
    readslicef_8_1_7 = tmp[0:0];
  end
  endfunction


  function [3:0] signext_4_1;
    input [0:0] vector;
  begin
    signext_4_1= {{3{vector[0]}}, vector};
  end
  endfunction


  function signed [9:0] conv_u2s_9_10 ;
    input [8:0]  vector ;
  begin
    conv_u2s_9_10 = {1'b0, vector};
  end
  endfunction


  function signed [11:0] conv_u2s_11_12 ;
    input [10:0]  vector ;
  begin
    conv_u2s_11_12 = {1'b0, vector};
  end
  endfunction


  function signed [5:0] conv_s2s_5_6 ;
    input signed [4:0]  vector ;
  begin
    conv_s2s_5_6 = {vector[4], vector};
  end
  endfunction


  function signed [4:0] conv_u2s_4_5 ;
    input [3:0]  vector ;
  begin
    conv_u2s_4_5 = {1'b0, vector};
  end
  endfunction


  function  [4:0] conv_u2u_4_5 ;
    input [3:0]  vector ;
  begin
    conv_u2u_4_5 = {1'b0, vector};
  end
  endfunction


  function signed [5:0] conv_u2s_5_6 ;
    input [4:0]  vector ;
  begin
    conv_u2s_5_6 = {1'b0, vector};
  end
  endfunction


  function  [1:0] conv_u2u_1_2 ;
    input [0:0]  vector ;
  begin
    conv_u2u_1_2 = {1'b0, vector};
  end
  endfunction


  function  [4:0] conv_s2u_3_5 ;
    input signed [2:0]  vector ;
  begin
    conv_s2u_3_5 = {{2{vector[2]}}, vector};
  end
  endfunction


  function  [3:0] conv_s2u_1_4 ;
    input signed [0:0]  vector ;
  begin
    conv_s2u_1_4 = {{3{vector[0]}}, vector};
  end
  endfunction


  function  [7:0] conv_u2u_7_8 ;
    input [6:0]  vector ;
  begin
    conv_u2u_7_8 = {1'b0, vector};
  end
  endfunction


  function signed [7:0] conv_u2s_7_8 ;
    input [6:0]  vector ;
  begin
    conv_u2s_7_8 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    markers
//  Generated from file(s):
//    2) $PROJECT_HOME/../markers_source/blur.c
// ------------------------------------------------------------------


module markers (
  vin, vout_rsc_z, vga_xy, volume_rsc_z, clk, en, arst_n
);
  input [89:0] vin;
  output [29:0] vout_rsc_z;
  input [19:0] vga_xy;
  output [7:0] volume_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [29:0] vout_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_out_stdreg #(.rscid(2),
  .width(30)) vout_rsc_mgc_out_stdreg (
      .d(vout_rsc_mgc_out_stdreg_d),
      .z(vout_rsc_z)
    );
  mgc_out_stdreg #(.rscid(4),
  .width(8)) volume_rsc_mgc_out_stdreg (
      .d(8'b0),
      .z(volume_rsc_z)
    );
  markers_core markers_core_inst (
      .vin(vin),
      .vga_xy(vga_xy),
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .vout_rsc_mgc_out_stdreg_d(vout_rsc_mgc_out_stdreg_d)
    );
endmodule



