
# Loop constraints
directive set /markers/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /markers/core/core:rlp/main CSTEPS_FROM {{. == 6} {.. == 0}}

# IO operation constraints
directive set /markers/core/core:rlp/main/asn#193 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#194 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#195 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#196 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#197 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#198 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#199 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#1 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#2 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#3 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#4 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#5 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#6 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#7 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#8 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#9 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#10 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#11 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#12 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#13 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#14 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#15 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#16 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#17 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#18 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#19 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#1:asn#20 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#206 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#207 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#208 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#209 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/asn#210 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/asn#211 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/asn#212 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/asn#213 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/asn#214 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/asn#218 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/asn#222 CSTEPS_FROM {{.. == 4}}
directive set /markers/core/core:rlp/main/asn#223 CSTEPS_FROM {{.. == 4}}
directive set /markers/core/core:rlp/main/asn#224 CSTEPS_FROM {{.. == 5}}
directive set /markers/core/core:rlp/main/io_write(volume:rsc.d) CSTEPS_FROM {{.. == 5}}
directive set /markers/core/core:rlp/main/io_write(vout:rsc.d) CSTEPS_FROM {{.. == 5}}

# Real operation constraints
directive set /markers/core/core:rlp/main/if:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/acc#7 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if:acc CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/and CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/and#1 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/and#2 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/and#3 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/and#4 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/and#5 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#3:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/aif#5:aif:acc CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/if#3:acc CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/else#3:aif:acc CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/else#3:aif#1:aif:acc CSTEPS_FROM {{.. == 1}}
directive set /markers/core/core:rlp/main/else#3:if:acc#2 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/else#3:if:acc CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/if#3:mux#1 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/if#3:mux#2 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/acc#1 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/mux#6 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/mux#7 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/acc#2 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/mux#9 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/mux#10 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/mux#12 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/deltax_red:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/if#10:acc CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/aif#29:acc CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/mux#14 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/mux#15 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/deltax_square_red:acc#1 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/mux#16 CSTEPS_FROM {{.. == 2}}
directive set /markers/core/core:rlp/main/deltax_blue:acc#1 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/if#12:acc CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/aif#33:acc CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/mux#18 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/mux#19 CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/aif#35:acc CSTEPS_FROM {{.. == 3}}
directive set /markers/core/core:rlp/main/deltay_square_red:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /markers/core/core:rlp/main/aif#37:aif:acc CSTEPS_FROM {{.. == 4}}
directive set /markers/core/core:rlp/main/deltax_square_blue:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /markers/core/core:rlp/main/else#13:aif:acc CSTEPS_FROM {{.. == 5}}
directive set /markers/core/core:rlp/main/deltay_square_blue:acc#1 CSTEPS_FROM {{.. == 5}}
directive set /markers/core/core:rlp/main/else#13:aif#1:aif:acc CSTEPS_FROM {{.. == 5}}
