// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   mf2915@EEWS305-026
//  Generated date: Sat May 07 13:17:42 2016
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    markers_core
// ------------------------------------------------------------------


module markers_core (
  vga_xy, clk, en, arst_n, vout_rsc_mgc_out_stdreg_d
);
  input [19:0] vga_xy;
  input clk;
  input en;
  input arst_n;
  output [29:0] vout_rsc_mgc_out_stdreg_d;
  reg [29:0] vout_rsc_mgc_out_stdreg_d;



  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : core
    // Interconnect Declarations
    reg aif_39_acc_cse_sg1_sva;
    reg land_13_lpi_dfm;
    reg aif_41_aif_acc_cse_sg1;

    begin : mainExit
      forever begin : main
        // C-Step 0 of Loop 'main'
        begin : waitLoop0Exit
          forever begin : waitLoop0
            @(posedge clk or negedge ( arst_n ));
            if ( ~ arst_n )
              disable mainExit;
            if ( en )
              disable waitLoop0Exit;
          end
        end
        // C-Step 1 of Loop 'main'
        aif_39_acc_cse_sg1_sva = readslicef_11_1_10((({1'b1 , (~ (vga_xy[9:0]))})
            + 11'b101001));
        if ( aif_39_acc_cse_sg1_sva ) begin
        end
        else begin
          aif_41_aif_acc_cse_sg1 = readslicef_11_1_10((({1'b1 , (~ (vga_xy[19:10]))})
              + 11'b101001));
        end
        land_13_lpi_dfm = ~(aif_41_aif_acc_cse_sg1 | aif_39_acc_cse_sg1_sva);
        vout_rsc_mgc_out_stdreg_d <= {(signext_10_1(~(aif_41_aif_acc_cse_sg1 | aif_39_acc_cse_sg1_sva
            | land_13_lpi_dfm))) , 10'b0 , ({{9{land_13_lpi_dfm}}, land_13_lpi_dfm})};
      end
    end
    aif_41_aif_acc_cse_sg1 = 1'b0;
    land_13_lpi_dfm = 1'b0;
    aif_39_acc_cse_sg1_sva = 1'b0;
    vout_rsc_mgc_out_stdreg_d <= 30'b0;
  end


  function [0:0] readslicef_11_1_10;
    input [10:0] vector;
    reg [10:0] tmp;
  begin
    tmp = vector >> 10;
    readslicef_11_1_10 = tmp[0:0];
  end
  endfunction


  function [9:0] signext_10_1;
    input [0:0] vector;
  begin
    signext_10_1= {{9{vector[0]}}, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    markers
//  Generated from file(s):
//    2) $PROJECT_HOME/../markers_source/blur.c
// ------------------------------------------------------------------


module markers (
  vin, vout_rsc_z, vga_xy, volume_rsc_z, clk, en, arst_n
);
  input [89:0] vin;
  output [29:0] vout_rsc_z;
  input [19:0] vga_xy;
  output [3:0] volume_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [29:0] vout_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_out_stdreg #(.rscid(2),
  .width(30)) vout_rsc_mgc_out_stdreg (
      .d(vout_rsc_mgc_out_stdreg_d),
      .z(vout_rsc_z)
    );
  mgc_out_stdreg #(.rscid(4),
  .width(4)) volume_rsc_mgc_out_stdreg (
      .d(4'b0),
      .z(volume_rsc_z)
    );
  markers_core markers_core_inst (
      .vga_xy(vga_xy),
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .vout_rsc_mgc_out_stdreg_d(vout_rsc_mgc_out_stdreg_d)
    );
endmodule



