// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   mf2915@EEWS305-026
//  Generated date: Sat May 07 13:18:58 2016
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    markers_core
// ------------------------------------------------------------------


module markers_core (
  vga_xy, clk, en, arst_n, vout_rsc_mgc_out_stdreg_d
);
  input [19:0] vga_xy;
  input clk;
  input en;
  input arst_n;
  output [29:0] vout_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations
  reg aif_41_aif_acc_cse_sg1;
  reg reg_vout_rsc_mgc_out_stdreg_d_1_reg;
  wire [10:0] aif_39_acc_itm;
  wire [11:0] nl_aif_39_acc_itm;
  wire aif_41_aif_acc_cse_sg1_mx0;
  wire land_13_lpi_dfm;
  reg reg_vout_rsc_mgc_out_stdreg_d_reg;


  // Interconnect Declarations for Component Instantiations 
  assign vout_rsc_mgc_out_stdreg_d = {({{9{reg_vout_rsc_mgc_out_stdreg_d_1_reg}},
      reg_vout_rsc_mgc_out_stdreg_d_1_reg}) , 10'b0 , ({{9{reg_vout_rsc_mgc_out_stdreg_d_reg}},
      reg_vout_rsc_mgc_out_stdreg_d_reg})};
  assign aif_41_aif_acc_cse_sg1_mx0 = MUX_s_1_2_2({(readslicef_11_1_10((({1'b1 ,
      (~ (vga_xy[19:10]))}) + 11'b101001))) , aif_41_aif_acc_cse_sg1}, aif_39_acc_itm[10]);
  assign nl_aif_39_acc_itm = ({1'b1 , (~ (vga_xy[9:0]))}) + 11'b101001;
  assign aif_39_acc_itm = nl_aif_39_acc_itm[10:0];
  assign land_13_lpi_dfm = ~(aif_41_aif_acc_cse_sg1_mx0 | (aif_39_acc_itm[10]));
  always @(posedge clk or negedge arst_n) begin
    if ( ~ arst_n ) begin
      aif_41_aif_acc_cse_sg1 <= 1'b0;
      reg_vout_rsc_mgc_out_stdreg_d_1_reg <= 1'b0;
      reg_vout_rsc_mgc_out_stdreg_d_reg <= 1'b0;
    end
    else begin
      if ( en ) begin
        aif_41_aif_acc_cse_sg1 <= aif_41_aif_acc_cse_sg1_mx0;
        reg_vout_rsc_mgc_out_stdreg_d_1_reg <= ~(aif_41_aif_acc_cse_sg1_mx0 | (aif_39_acc_itm[10])
            | land_13_lpi_dfm);
        reg_vout_rsc_mgc_out_stdreg_d_reg <= land_13_lpi_dfm;
      end
    end
  end

  function [0:0] MUX_s_1_2_2;
    input [1:0] inputs;
    input [0:0] sel;
    reg [0:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[1:1];
      end
      1'b1 : begin
        result = inputs[0:0];
      end
      default : begin
        result = inputs[1:1];
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function [0:0] readslicef_11_1_10;
    input [10:0] vector;
    reg [10:0] tmp;
  begin
    tmp = vector >> 10;
    readslicef_11_1_10 = tmp[0:0];
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    markers
//  Generated from file(s):
//    2) $PROJECT_HOME/../markers_source/blur.c
// ------------------------------------------------------------------


module markers (
  vin, vout_rsc_z, vga_xy, volume_rsc_z, clk, en, arst_n
);
  input [89:0] vin;
  output [29:0] vout_rsc_z;
  input [19:0] vga_xy;
  output [3:0] volume_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [29:0] vout_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_out_stdreg #(.rscid(2),
  .width(30)) vout_rsc_mgc_out_stdreg (
      .d(vout_rsc_mgc_out_stdreg_d),
      .z(vout_rsc_z)
    );
  mgc_out_stdreg #(.rscid(4),
  .width(4)) volume_rsc_mgc_out_stdreg (
      .d(4'b0),
      .z(volume_rsc_z)
    );
  markers_core markers_core_inst (
      .vga_xy(vga_xy),
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .vout_rsc_mgc_out_stdreg_d(vout_rsc_mgc_out_stdreg_d)
    );
endmodule



