// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   mf2915@EEWS104A-015
//  Generated date: Wed May 04 11:40:08 2016
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    markers_core
// ------------------------------------------------------------------


module markers_core (
  vin, clk, en, arst_n, vout_rsc_mgc_out_stdreg_d
);
  input [89:0] vin;
  input clk;
  input en;
  input arst_n;
  output [29:0] vout_rsc_mgc_out_stdreg_d;
  reg [29:0] vout_rsc_mgc_out_stdreg_d;



  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : core
    // Interconnect Declarations
    reg slc_svs;
    reg land_2_sva_1;
    reg land_2_lpi_dfm;
    reg aif_1_slc_svs;
    reg aif_1_land_sva_1;
    reg land_1_lpi_dfm;
    reg aif_5_slc_svs;
    reg aif_5_land_sva_1;
    reg else_slc_svs;
    reg else_land_2_sva_1;
    reg else_land_2_lpi_dfm;
    reg else_aif_1_slc_svs;
    reg else_aif_1_land_sva_1;
    reg else_land_1_lpi_dfm;
    reg else_aif_2_slc_svs;
    reg else_aif_2_land_sva_1;
    reg else_land_lpi_dfm;
    reg [7:0] red_out_sg1_sva_1;
    reg [7:0] green_out_sg1_sva_1;
    reg [7:0] blue_out_sg1_sva_1;
    reg [7:0] mux_8;
    reg [7:0] mux_9;
    reg [7:0] mux_10;

    begin : mainExit
      forever begin : main
        // C-Step 0 of Loop 'main'
        begin : waitLoop0Exit
          forever begin : waitLoop0
            @(posedge clk or negedge ( arst_n ));
            if ( ~ arst_n )
              disable mainExit;
            if ( en )
              disable waitLoop0Exit;
          end
        end
        // C-Step 1 of Loop 'main'
        blue_out_sg1_sva_1 = 8'b0;
        green_out_sg1_sva_1 = 8'b0;
        red_out_sg1_sva_1 = 8'b0;
        else_aif_2_land_sva_1 = 1'b0;
        else_aif_1_land_sva_1 = 1'b0;
        else_land_2_sva_1 = 1'b0;
        aif_5_land_sva_1 = 1'b0;
        aif_1_land_sva_1 = 1'b0;
        land_2_sva_1 = 1'b0;
        slc_svs = readslicef_5_1_4((conv_u2u_4_5(vin[29:26]) + 5'b11011));
        if ( slc_svs ) begin
        end
        else begin
          land_2_sva_1 = ~ (readslicef_8_1_7((({1'b1 , (~ (vin[29:23]))}) + 8'b1001001)));
        end
        land_2_lpi_dfm = land_2_sva_1 & (~ slc_svs);
        if ( land_2_lpi_dfm ) begin
          aif_1_slc_svs = readslicef_8_1_7((conv_u2u_7_8(vin[19:13]) + 8'b10110101));
          if ( aif_1_slc_svs ) begin
          end
          else begin
            aif_1_land_sva_1 = ~ (readslicef_8_1_7((conv_u2s_7_8(~ (vin[18:12]))
                + 8'b11100111)));
          end
        end
        land_1_lpi_dfm = aif_1_land_sva_1 & (~ aif_1_slc_svs) & land_2_lpi_dfm;
        if ( land_1_lpi_dfm ) begin
          aif_5_slc_svs = readslicef_8_1_7((conv_u2u_7_8(vin[9:3]) + 8'b11110001));
          if ( aif_5_slc_svs ) begin
          end
          else begin
            aif_5_land_sva_1 = ~ (readslicef_9_1_8((({1'b1 , (~ (vin[9:2]))}) + 9'b1101101)));
          end
        end
        if ( aif_5_land_sva_1 & (~ aif_5_slc_svs) & land_1_lpi_dfm ) begin
          mux_8 = vin[29:22];
          mux_9 = vin[19:12];
          mux_10 = vin[9:2];
        end
        else begin
          else_slc_svs = readslicef_8_1_7((conv_u2u_7_8(vin[29:23]) + 8'b10101011));
          if ( else_slc_svs ) begin
          end
          else begin
            else_land_2_sva_1 = ~ (readslicef_8_1_7((conv_u2s_7_8(~ (vin[28:22]))
                + 8'b11011111)));
          end
          else_land_2_lpi_dfm = else_land_2_sva_1 & (~ else_slc_svs);
          if ( else_land_2_lpi_dfm ) begin
            else_aif_1_slc_svs = readslicef_9_1_8((conv_u2s_8_9(vin[19:12]) + 9'b101000111));
            if ( else_aif_1_slc_svs ) begin
            end
            else begin
              else_aif_1_land_sva_1 = ~ (readslicef_6_1_5((conv_u2s_5_6(~ (vin[18:14]))
                  + 6'b111011)));
            end
          end
          else_land_1_lpi_dfm = else_aif_1_land_sva_1 & (~ else_aif_1_slc_svs) &
              else_land_2_lpi_dfm;
          if ( else_land_1_lpi_dfm ) begin
            else_aif_2_slc_svs = readslicef_9_1_8((conv_u2s_8_9(vin[9:2]) + 9'b111001111));
            if ( else_aif_2_slc_svs ) begin
            end
            else begin
              else_aif_2_land_sva_1 = ~ (readslicef_8_1_7((({1'b1 , (~ (vin[9:3]))})
                  + 8'b1001011)));
            end
          end
          else_land_lpi_dfm = else_aif_2_land_sva_1 & (~ else_aif_2_slc_svs) & else_land_1_lpi_dfm;
          if ( else_land_lpi_dfm ) begin
            red_out_sg1_sva_1 = vin[29:22];
            green_out_sg1_sva_1 = vin[19:12];
            blue_out_sg1_sva_1 = vin[9:2];
          end
          mux_8 = red_out_sg1_sva_1 & ({{7{else_land_lpi_dfm}}, else_land_lpi_dfm});
          mux_9 = green_out_sg1_sva_1 & ({{7{else_land_lpi_dfm}}, else_land_lpi_dfm});
          mux_10 = blue_out_sg1_sva_1 & ({{7{else_land_lpi_dfm}}, else_land_lpi_dfm});
        end
        vout_rsc_mgc_out_stdreg_d <= {mux_8 , 2'b0 , mux_9 , 2'b0 , mux_10 , 2'b0};
      end
    end
    mux_10 = 8'b0;
    mux_9 = 8'b0;
    mux_8 = 8'b0;
    blue_out_sg1_sva_1 = 8'b0;
    green_out_sg1_sva_1 = 8'b0;
    red_out_sg1_sva_1 = 8'b0;
    else_land_lpi_dfm = 1'b0;
    else_aif_2_land_sva_1 = 1'b0;
    else_aif_2_slc_svs = 1'b0;
    else_land_1_lpi_dfm = 1'b0;
    else_aif_1_land_sva_1 = 1'b0;
    else_aif_1_slc_svs = 1'b0;
    else_land_2_lpi_dfm = 1'b0;
    else_land_2_sva_1 = 1'b0;
    else_slc_svs = 1'b0;
    aif_5_land_sva_1 = 1'b0;
    aif_5_slc_svs = 1'b0;
    land_1_lpi_dfm = 1'b0;
    aif_1_land_sva_1 = 1'b0;
    aif_1_slc_svs = 1'b0;
    land_2_lpi_dfm = 1'b0;
    land_2_sva_1 = 1'b0;
    slc_svs = 1'b0;
    vout_rsc_mgc_out_stdreg_d <= 30'b0;
  end


  function [0:0] readslicef_5_1_4;
    input [4:0] vector;
    reg [4:0] tmp;
  begin
    tmp = vector >> 4;
    readslicef_5_1_4 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_8_1_7;
    input [7:0] vector;
    reg [7:0] tmp;
  begin
    tmp = vector >> 7;
    readslicef_8_1_7 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_9_1_8;
    input [8:0] vector;
    reg [8:0] tmp;
  begin
    tmp = vector >> 8;
    readslicef_9_1_8 = tmp[0:0];
  end
  endfunction


  function [0:0] readslicef_6_1_5;
    input [5:0] vector;
    reg [5:0] tmp;
  begin
    tmp = vector >> 5;
    readslicef_6_1_5 = tmp[0:0];
  end
  endfunction


  function  [4:0] conv_u2u_4_5 ;
    input [3:0]  vector ;
  begin
    conv_u2u_4_5 = {1'b0, vector};
  end
  endfunction


  function  [7:0] conv_u2u_7_8 ;
    input [6:0]  vector ;
  begin
    conv_u2u_7_8 = {1'b0, vector};
  end
  endfunction


  function signed [7:0] conv_u2s_7_8 ;
    input [6:0]  vector ;
  begin
    conv_u2s_7_8 = {1'b0, vector};
  end
  endfunction


  function signed [8:0] conv_u2s_8_9 ;
    input [7:0]  vector ;
  begin
    conv_u2s_8_9 = {1'b0, vector};
  end
  endfunction


  function signed [5:0] conv_u2s_5_6 ;
    input [4:0]  vector ;
  begin
    conv_u2s_5_6 = {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    markers
//  Generated from file(s):
//    2) $PROJECT_HOME/../markers_source/blur.c
// ------------------------------------------------------------------


module markers (
  vin, vout_rsc_z, vga_xy, volume_rsc_z, clk, en, arst_n
);
  input [89:0] vin;
  output [29:0] vout_rsc_z;
  input [19:0] vga_xy;
  output [7:0] volume_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire [29:0] vout_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_out_stdreg #(.rscid(2),
  .width(30)) vout_rsc_mgc_out_stdreg (
      .d(vout_rsc_mgc_out_stdreg_d),
      .z(vout_rsc_z)
    );
  mgc_out_stdreg #(.rscid(4),
  .width(8)) volume_rsc_mgc_out_stdreg (
      .d(8'b0),
      .z(volume_rsc_z)
    );
  markers_core markers_core_inst (
      .vin(vin),
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .vout_rsc_mgc_out_stdreg_d(vout_rsc_mgc_out_stdreg_d)
    );
endmodule



